### PR TITLE
Pop in FifoWindow in Rust no longer returns value

### LINKED ISSUE #44: In Rust trait, should `pop` return a value?
@hirzel brought this up in a PR:

> I think pop should not return anything. I can see from the implementation of some of the aggregation algorithms that it lowers the oldest item and returns that. There are two problems with that. First, it is wasteful to do the lowering if that return value gets discarded by the caller. Second, and more importantly, not all aggregation algorithms hold on to that oldest item, so it is unavailable to be lowered and returned. Specifically, Two-Stacks Lite and DABA Lite don't keep around singleton partials for the front portion of the queue, since that portion is optimized for eviction, where it makes more sense to keep around partials for larger sublists.

I had a similar reaction when @segeljakt first designed `FifoWindow`. The main reason for doing it is that is lines up with Rust conventions. Regarding point 1, I don't think it's a major concern: if the return value of `pop` is unused, and the call to `pop` itself is inlined, dead-code elimination should avoid any overhead (even the call to lower should go away).

Point 2 is more of a concern, but I admit I don't fully follow it. Is the problem that in some cases, the partial result from the thing being evicted is nonsensical to return?

### PR DESCRIPTION
**Pull request by scotts**
Closes #44

### CODE REVIEW

**Review by segeljakt — APPROVED** [review]
LGTM, does it make sense to also make the same modification to `evict` in `TimeWindow`?

**Comment by ktangwon** [comment]
This looks great. Yes, I think `evict` in the `TimeWindow` should be updated as well, as @segeljakt has mentioned. In the case of a time window, the data structure should indicate whether or not the given timestamp leads to a successful eviction. But I'm not 100% sure what we should make it return, e.g., a flag or some real data. I realize this is a separate discussion (should it go into a new issue?).

**Review by ktangwon — APPROVED** [review]

**Review by hirzel — APPROVED** [review]
Thank you, I think this makes the code cleaner.

**Comment by scotts** [comment]
Excellent, I'll make a separate issue to track `evict` in `TimeWindow`.

**Pull request merged**
