### PR TITLE
Rust implementation of Recalculate-From-Scratch (ReCalc)

### PR DESCRIPTION
**Pull request by segeljakt**
Here is the first algorithm implementation along with two tests.

### CODE REVIEW

**Comment by scotts** [comment]
This PR has a duplicate commit ([`2d8bc3df`](https://github.com/IBM/sliding-window-aggregators/pull/12/commits/2d8bc3df7311a334fda59d581fd6c0f804e2fc5d) that was in PR #11. Please rebase your branch on master.

**Comment by scotts** [comment]
Are you okay changing the name to "Recalculate-From-Scratch", or something similar to that? That is the name we have used for the naive, recompute-everything aggregator in papers, and then we tend to refer to it as "recalc" casually. Our current C++ version is [ReCalc](https://github.com/IBM/sliding-window-aggregators/blob/master/cpp/src/ReCalc.hpp).

**Comment by segeljakt** [comment]
Yes, no problem. One moment.

**Comment by segeljakt** [comment]
I don't know why I wrote "Remove-From-Scratch", it should have been Recalculate-From-Scratch :)

**Comment by scotts** [comment]
Excellent, I figured it was something like a mix of "subtract-on-evict" and "recalc-from-scratch." :)

We don't have any storage rules, if I understand what you mean. All of our implementations also store everything in memory, and we've never given consideration to what it would mean to spill to disk. I think that could actually become an interesting research direction. While some of the algorithms exhibit better cache locality than others, that's more a side-effect of designing for a particular complexity.

**Pull request merged**
